server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: configServer
  cloud:
    config:
      server:
        native:
          search-locations: c:/Users/jorge_neto/Desktop/workspace/Alura/spring boot/micro-repo
