server:
  port: 8888

spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jgsaba/springcloud-lrng1
          search-paths: micro-repo/fornecedor, micro-repo/loja, micro-repo/transportador
